### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by lukejkelly** [lukejkelly/CoupledPhylogenetics#1]
- [x] Figures for multiple coupling lags
- [x] Reorganise directory structure
- [x] Separate synthetic data generation so that we can keep track of it
